name: .NET Core Test and Publish

on: pull_request

env:
  DOTNET_VERSION: 2.1

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Test
      run: |
        sudo apt-get --assume-yes install libleveldb-dev libsnappy-dev libc6-dev
        find tests -name *.csproj | xargs -I % dotnet add % package coverlet.msbuild
        dotnet test SimplePolicy.UnitTests /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=${GITHUB_WORKSPACE}/coverage/lcov
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
